import qrcode
from PIL import Image

# <<<<<<Simple Use>>>>>>>
# img = qrcode.make('Hello')
# img.show()

# <<<<<Advanced Uses>>>>>>

# making a qr object
qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_H,
    box_size=5,
    border=1,
)

# adding data and converting it to an image
qr.add_data("This is a sample QR code generated by python")
qr.make(fit=True)
img = qr.make_image(fill_color="black", back_color="white").convert("RGB")

# # adding an overlay
# logo_display = Image.open('input.jpg')
# logo_display.thumbnail((60, 60))
# # logo_display.show()

# logo_pos = ((img.size[0] - logo_display.size[0]) // 2, (img.size[1] - logo_display.size[1]) // 2)
# img.paste(logo_display, logo_pos)
# # img.show()


# pasting the QR code into another image
img.thumbnail((100, 100))
img2 = Image.open("input.jpg")
img2.paste(img, (0, 0))

img2.save("output.jpg")
# img2.show()
